version: "3.9"
services:
  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
    container_name: pos_api
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mysql
    volumes:
      - ./app:/app
  mysql:
    image: mysql:5.7
    container_name: pos_mysql
    # command: mysqld --user=root
    # command: mysql -u root -p
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 5s
      retries: 10