version: "3.9"
services:
  ### ===================
  ### APP SERVICE
  ### ===================
  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
    container_name: pos_api
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mysql
    volumes:
      - ./app:/app
    networks:
      - pos_network

  ### ===================
  ### DB SERVICE
  ### ===================
  mysql:
    image: mysql:5.7
    container_name: pos_mysql
    # command: mysqld --user=root
    # command: mysql -u root -p
    ports:
      - 3306:3306
    networks:
      - pos_network
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      # - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes: 
          - ./docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 5s
      retries: 10

### ===================
### SWAGGER SERVICE
### ===================
  doc:
    build: 
      context: .
      dockerfile: swagger/Dockerfile
    container_name: doc_pos_api
    environment:
      - URL=http://localhost:9090/api-spec
      - SWAGGER_JSON=/API-SPEC.json
    volumes:
      - ./API-SPEC.json:/API-SPEC.json
    ports:
      - 9090:8080
    networks:
      - pos_network
  
networks:
  pos_network:
